version: '3.9'
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: events-api-deploy
    command: sh -c "/scripts/run.sh"
    volumes:
      - ./theatreevents:/events
      - static:/events/static
    ports:
      - '8000:8000'
    env_file:
      - env/prod/.env
    depends_on:
      - db

  proxy:
    build: ./proxy
    container_name: events-proxy
    ports:
      - '80:80'
    volumes:
      - static:/static
    depends_on:
      - api

  db:
    image: postgres:15.2-alpine
    container_name: events-db
    volumes:
      - theatrekedb:/var/lib/postgresql/data/theatrekedb
    ports:
      - "5432:5432"
    env_file:
      - env/prod/.env.db

volumes:
  theatrekedb:
  static: