version: '3.9'
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: events-api
    volumes:
      - ./theatre-events:/events
      - static:/events/static
    ports:
      - '8000:8000'
    env_file:
      - env/dev/.env
    depends_on:
      - db

  proxy:
    build: ./proxy
    container_name: events-proxy
    ports:
      - '80:80'
    volumes:
      - static:/static
    depends_on:
      - api

  db:
    image: postgres:15.2-alpine
    container_name: events-db
    volumes:
      - theatrekedb:/events/theatrekedb
    ports:
      - "5432:5432"
    env_file:
      - env/dev/.env.db

  pgadmin:
    container_name: pgadmin4-container
    image: dpage/pgadmin4
    restart: always
    env_file:
      - env/dev/.env.pgadmin
    ports:
      - "5001:80"

volumes:
  theatrekedb:
  static: